# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0002_dailyspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyspecial',
            name='price',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
