# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering_system', '0003_dailyspecial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
